create schema if not exists petroagent;

create table if not exists petroagent.project_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  source text not null default 'web'
);

alter table petroagent.project_likes enable row level security;

create policy "Anyone can register public project likes"
  on petroagent.project_likes
  for insert
  to anon, authenticated
  with check (source = 'web');

create policy "Anyone can count public project likes"
  on petroagent.project_likes
  for select
  to anon, authenticated
  using (true);

grant usage on schema petroagent to anon, authenticated, service_role;
grant select, insert on table petroagent.project_likes to anon, authenticated;
grant usage, select on sequence petroagent.project_likes_id_seq to anon, authenticated;

-- Supabase Data API note:
-- Add the `petroagent` schema to Project Settings > Data API > Exposed schemas
-- so supabase-js can access petroagent.project_likes from the application API.
