create schema if not exists petroagent;

create table if not exists petroagent.reports (
  id bigint generated by default as identity primary key,
  engine text not null,
  payload jsonb not null,
  source_url text,
  created_at timestamp with time zone not null default now()
);

alter table petroagent.reports enable row level security;

create policy "Public select reports" on petroagent.reports
  for select to anon, authenticated using (true);

grant usage on schema petroagent to anon, authenticated, service_role;
grant select, insert on table petroagent.reports to anon, authenticated;
grant usage, select on sequence petroagent.reports_id_seq to anon, authenticated;

-- Note: Add `petroagent` schema to Supabase Data API exposed schemas if using the hosted Data API.
