create table if not exists petroagent.agent_execution_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  started_at timestamp with time zone not null default now(),
  finished_at timestamp with time zone,
  status text not null check (status in ('started', 'saved', 'failed')),
  origin text not null,
  engine text,
  report_id bigint references petroagent.agent_reports(id) on delete set null,
  source_count integer not null default 0 check (source_count >= 0),
  error_message text
);

create index if not exists agent_execution_logs_created_at_idx
  on petroagent.agent_execution_logs (created_at desc);

create index if not exists agent_execution_logs_status_idx
  on petroagent.agent_execution_logs (status);

alter table petroagent.agent_execution_logs enable row level security;

create policy "Service role can manage agent execution logs"
  on petroagent.agent_execution_logs
  for all
  to service_role
  using (true)
  with check (true);

grant all on table petroagent.agent_execution_logs to service_role;
grant usage, select on sequence petroagent.agent_execution_logs_id_seq to service_role;

-- Logs operacionais não recebem grant para anon/authenticated.
-- Mesmo com o schema petroagent exposto na Data API, RLS e grants mantêm a
-- tabela restrita ao backend com service_role.
