create schema if not exists petroagent;

create table if not exists petroagent.sources (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  source_type text not null,
  title text,
  url text,
  published_at timestamp with time zone,
  raw_content text,
  processed boolean not null default false
);

create table if not exists petroagent.market_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  event_date timestamp with time zone,
  event_type text not null,
  title text not null,
  summary text,
  source_id bigint references petroagent.sources(id) on delete set null,
  relevance_score integer check (
    relevance_score is null
    or (relevance_score >= 0 and relevance_score <= 100)
  )
);

create table if not exists petroagent.agent_reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  title text not null,
  summary text not null,
  sentiment text,
  attention_points text[],
  source_count integer not null default 0 check (source_count >= 0),
  model_used text
);

create table if not exists petroagent.market_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  ticker text not null,
  price numeric,
  variation numeric,
  volume numeric,
  source text,
  snapshot_time timestamp with time zone
);

create index if not exists sources_processed_idx
  on petroagent.sources (processed);

create index if not exists sources_published_at_idx
  on petroagent.sources (published_at desc);

create index if not exists market_events_event_date_idx
  on petroagent.market_events (event_date desc);

create index if not exists market_events_source_id_idx
  on petroagent.market_events (source_id);

create index if not exists agent_reports_created_at_idx
  on petroagent.agent_reports (created_at desc);

create index if not exists market_snapshots_ticker_snapshot_time_idx
  on petroagent.market_snapshots (ticker, snapshot_time desc);

alter table petroagent.sources enable row level security;
alter table petroagent.market_events enable row level security;
alter table petroagent.agent_reports enable row level security;
alter table petroagent.market_snapshots enable row level security;

create policy "Anyone can read public sources"
  on petroagent.sources
  for select
  to anon, authenticated
  using (true);

create policy "Service role can manage sources"
  on petroagent.sources
  for all
  to service_role
  using (true)
  with check (true);

create policy "Anyone can read public market events"
  on petroagent.market_events
  for select
  to anon, authenticated
  using (true);

create policy "Service role can manage market events"
  on petroagent.market_events
  for all
  to service_role
  using (true)
  with check (true);

create policy "Anyone can read public agent reports"
  on petroagent.agent_reports
  for select
  to anon, authenticated
  using (true);

create policy "Service role can manage agent reports"
  on petroagent.agent_reports
  for all
  to service_role
  using (true)
  with check (true);

create policy "Anyone can read public market snapshots"
  on petroagent.market_snapshots
  for select
  to anon, authenticated
  using (true);

create policy "Service role can manage market snapshots"
  on petroagent.market_snapshots
  for all
  to service_role
  using (true)
  with check (true);

grant usage on schema petroagent to anon, authenticated, service_role;

grant select on table
  petroagent.sources,
  petroagent.market_events,
  petroagent.agent_reports,
  petroagent.market_snapshots
to anon, authenticated;

grant all on table
  petroagent.sources,
  petroagent.market_events,
  petroagent.agent_reports,
  petroagent.market_snapshots
to service_role;

grant usage, select on sequence
  petroagent.sources_id_seq,
  petroagent.market_events_id_seq,
  petroagent.agent_reports_id_seq,
  petroagent.market_snapshots_id_seq
to service_role;

-- Supabase Data API note:
-- Keep the `petroagent` schema exposed in Project Settings > Data API.
-- Public clients can read these tables, while writes are reserved for backend
-- jobs using service_role in future collection and report-generation phases.
